language: node_js
sudo: required
addons:
  chrome: stable
node_js:
  - 10
os: linux
cache:
  yarn: true
branches:
  only:
    - master
    - dev
install:
  - |
    yarn
script:
  - |
    yarn lint
after_success:
  - |
    cat ./test/coverage/lcov.info | ./node_modules/.bin/codecov
